#include "regressionrunner.h"

#include "pointcloudprocessor.h"

#include <QCommandLineOption>
#include <QCommandLineParser>
#include <QCoreApplication>
#include <QTextStream>
#include <QDateTime>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QHash>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QMatrix4x4>
#include <QRegularExpression>
#include <QSaveFile>
#include <QXmlStreamReader>

#include <cmath>

namespace {
struct PoseRecord {
    int scan = -1;
    QVector<double> start;
    QVector<double> end;
};

bool writeAsciiPly(const QString &path, const QVector<pointcloud::Point3D> &points,
                   QString *error)
{
    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly)) {
        if (error) *error = QStringLiteral("无法创建输出文件：%1").arg(path);
        return false;
    }
    QTextStream stream(&file);
    stream.setLocale(QLocale::c());
    stream.setRealNumberNotation(QTextStream::ScientificNotation);
    stream.setRealNumberPrecision(9);
    stream << "ply\nformat ascii 1.0\n"
              "comment generated by pointcloudstitch transform-only regression\n"
           << "element vertex " << points.size() << "\n"
              "property float x\nproperty float y\nproperty float z\n"
              "end_header\n";
    for (const pointcloud::Point3D &point : points)
        stream << point.x << ' ' << point.y << ' ' << point.z << '\n';
    stream.flush();
    if (stream.status() != QTextStream::Ok || !file.commit()) {
        if (error) *error = QStringLiteral("写入 PLY 数据失败：%1").arg(path);
        return false;
    }
    return true;
}

QMatrix4x4 poseMatrix(const QVector<double> &pose)
{
    QMatrix4x4 matrix;
    matrix.setToIdentity();
    matrix.rotate(float(pose.value(5)), 0.0f, 0.0f, 1.0f);
    matrix.rotate(float(pose.value(4)), 0.0f, 1.0f, 0.0f);
    matrix.rotate(float(pose.value(3)), 1.0f, 0.0f, 0.0f);
    matrix(0, 3) = float(pose.value(0));
    matrix(1, 3) = float(pose.value(1));
    matrix(2, 3) = float(pose.value(2));
    return matrix;
}

bool readCalibration(const QString &path, QMatrix4x4 *matrix, QString *error)
{
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        *error = QStringLiteral("无法打开标定文件：%1").arg(path);
        return false;
    }
    QXmlStreamReader xml(&file);
    bool inside = false;
    QVector<double> rotation, translation;
    while (!xml.atEnd()) {
        xml.readNext();
        if (xml.isEndElement() && xml.name() == QStringLiteral("RTmatDepth2robot")) inside = false;
        if (!xml.isStartElement()) continue;
        if (xml.name() == QStringLiteral("RTmatDepth2robot")) inside = true;
        else if (inside && xml.name() == QStringLiteral("RotMat")) {
            rotation.resize(9);
            for (int row = 0; row < 3; ++row)
                for (int column = 0; column < 3; ++column) {
                    bool ok = false;
                    rotation[row * 3 + column] = xml.attributes()
                        .value(QStringLiteral("r%1%2").arg(row).arg(column)).toDouble(&ok);
                    if (!ok) rotation.clear();
                }
        } else if (inside && xml.name() == QStringLiteral("TVec")) {
            translation.resize(3);
            for (int index = 0; index < 3; ++index) {
                bool ok = false;
                translation[index] = xml.attributes().value(QStringLiteral("t%1").arg(index)).toDouble(&ok);
                if (!ok) translation.clear();
            }
        }
    }
    if (xml.hasError() || rotation.size() != 9 || translation.size() != 3) {
        *error = xml.hasError() ? xml.errorString()
                                : QStringLiteral("XML 中 RTmatDepth2robot/RotMat/TVec 不完整");
        return false;
    }
    matrix->setToIdentity();
    for (int row = 0; row < 3; ++row) {
        for (int column = 0; column < 3; ++column) (*matrix)(row, column) = float(rotation[row * 3 + column]);
        (*matrix)(row, 3) = float(translation[row]);
    }
    return true;
}

bool readPoseInfo(const QString &path, QHash<int, PoseRecord> *records, QString *error)
{
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        *error = QStringLiteral("无法打开位姿文件：%1").arg(path);
        return false;
    }
    const QString number = QStringLiteral("([-+]?(?:\\d+(?:\\.\\d*)?|\\.\\d+)(?:[eE][-+]?\\d+)?)");
    const QRegularExpression pattern(
        QStringLiteral("A(\\d+)\\s+Start\\s+X%1\\s+Y%1\\s+Z%1\\s+RX%1\\s+RY%1\\s+RZ%1\\s*;\\s*END\\s+X%1\\s+Y%1\\s+Z%1\\s+RX%1\\s+RY%1\\s+RZ%1")
            .arg(number), QRegularExpression::CaseInsensitiveOption);
    while (!file.atEnd()) {
        const QString line = QString::fromUtf8(file.readLine()).trimmed();
        const auto match = pattern.match(line);
        if (!match.hasMatch()) continue;
        PoseRecord record;
        record.scan = match.captured(1).toInt();
        bool ok = true;
        for (int index = 0; index < 6; ++index) record.start.push_back(match.captured(index + 2).toDouble(&ok));
        for (int index = 0; index < 6; ++index) record.end.push_back(match.captured(index + 8).toDouble(&ok));
        if (!ok) {
            *error = QStringLiteral("位姿行包含无效数字：%1").arg(line);
            return false;
        }
        records->insert(record.scan, record);
    }
    if (records->size() < 2) {
        *error = QStringLiteral("位姿文件中少于两组有效 Start/End");
        return false;
    }
    return true;
}

QVector<float> parseLevels(const QString &text, QString *error)
{
    QVector<float> result;
    const QStringList parts = text.split(QRegularExpression(QStringLiteral("[\\s,，/]+")), Qt::SkipEmptyParts);
    for (const QString &part : parts) {
        bool ok = false;
        const float value = part.toFloat(&ok);
        if (!ok || value <= 0) {
            *error = QStringLiteral("参数层级必须包含三个正数：%1").arg(text);
            return {};
        }
        result.push_back(value);
    }
    if (result.size() != 3) *error = QStringLiteral("参数层级必须恰好包含三个数：%1").arg(text);
    return result;
}

QJsonArray vectorJson(const QVector<double> &values)
{
    QJsonArray result;
    for (double value : values) result.append(value);
    return result;
}

QJsonObject diagnosticJson(const pointcloud::IcpDiagnostics &diagnostic,
                           const pointcloud::IcpOptions &options)
{
    QJsonObject item;
    item.insert(QStringLiteral("target_cloud_index"), diagnostic.targetCloudIndex);
    item.insert(QStringLiteral("source_cloud_index"), diagnostic.sourceCloudIndex);
    item.insert(QStringLiteral("file"), diagnostic.filePath);
    item.insert(QStringLiteral("attempted"), diagnostic.attempted);
    item.insert(QStringLiteral("accepted"), diagnostic.accepted);
    item.insert(QStringLiteral("reason"), diagnostic.reason);
    item.insert(QStringLiteral("source_crop_points"), diagnostic.sourceCropCount);
    item.insert(QStringLiteral("target_crop_points"), diagnostic.targetCropCount);
    item.insert(QStringLiteral("actual_overlap_source_points"), diagnostic.actualOverlapSourceCount);
    item.insert(QStringLiteral("actual_overlap_target_points"), diagnostic.actualOverlapTargetCount);
    item.insert(QStringLiteral("overlap_minimum_retention"), diagnostic.minimumOverlapRetention);
    item.insert(QStringLiteral("overlap_constrained_step_reductions"), diagnostic.overlapConstrainedStepReductions);
    item.insert(QStringLiteral("degenerate"), diagnostic.degenerate);
    item.insert(QStringLiteral("observable_dof"), diagnostic.observableDof);
    item.insert(QStringLiteral("hessian_condition_ratio"), diagnostic.conditionRatio);
    item.insert(QStringLiteral("degenerate_projected_iterations"), diagnostic.projectedIterations);
    item.insert(QStringLiteral("projected_overlap_width_mm"), diagnostic.projectedOverlapWidth);
    item.insert(QStringLiteral("nearest_distance_p50_mm"), diagnostic.nearestDistanceP50);
    item.insert(QStringLiteral("nearest_distance_p90_mm"), diagnostic.nearestDistanceP90);
    item.insert(QStringLiteral("nearest_distance_p95_mm"), diagnostic.nearestDistanceP95);
    item.insert(QStringLiteral("coverage_within_3mm"), diagnostic.coverageWithin3mm);
    item.insert(QStringLiteral("coverage_within_5mm"), diagnostic.coverageWithin5mm);
    item.insert(QStringLiteral("coverage_within_10mm"), diagnostic.coverageWithin10mm);
    item.insert(QStringLiteral("nearest_distance_p50_after_prealignment_mm"), diagnostic.nearestDistanceP50AfterPrealignment);
    item.insert(QStringLiteral("nearest_distance_p90_after_prealignment_mm"), diagnostic.nearestDistanceP90AfterPrealignment);
    item.insert(QStringLiteral("nearest_distance_p95_after_prealignment_mm"), diagnostic.nearestDistanceP95AfterPrealignment);
    item.insert(QStringLiteral("coverage_within_3mm_after_prealignment"), diagnostic.coverageWithin3mmAfterPrealignment);
    item.insert(QStringLiteral("coverage_within_5mm_after_prealignment"), diagnostic.coverageWithin5mmAfterPrealignment);
    item.insert(QStringLiteral("coverage_within_10mm_after_prealignment"), diagnostic.coverageWithin10mmAfterPrealignment);
    item.insert(QStringLiteral("structural_source_points"), diagnostic.structuralSourcePoints);
    item.insert(QStringLiteral("structural_target_points"), diagnostic.structuralTargetPoints);
    item.insert(QStringLiteral("structural_source_matched_points"), diagnostic.structuralSourceMatchedPoints);
    item.insert(QStringLiteral("structural_target_matched_points"), diagnostic.structuralTargetMatchedPoints);
    item.insert(QStringLiteral("structural_source_to_target_p50_mm"), diagnostic.structuralSourceToTargetP50);
    item.insert(QStringLiteral("structural_source_to_target_p90_mm"), diagnostic.structuralSourceToTargetP90);
    item.insert(QStringLiteral("structural_source_to_target_p95_mm"), diagnostic.structuralSourceToTargetP95);
    item.insert(QStringLiteral("structural_target_to_source_p50_mm"), diagnostic.structuralTargetToSourceP50);
    item.insert(QStringLiteral("structural_target_to_source_p90_mm"), diagnostic.structuralTargetToSourceP90);
    item.insert(QStringLiteral("structural_target_to_source_p95_mm"), diagnostic.structuralTargetToSourceP95);
    item.insert(QStringLiteral("structural_source_to_target_coverage_3mm"), diagnostic.structuralSourceToTargetCoverage3mm);
    item.insert(QStringLiteral("structural_source_to_target_coverage_5mm"), diagnostic.structuralSourceToTargetCoverage5mm);
    item.insert(QStringLiteral("structural_source_to_target_coverage_10mm"), diagnostic.structuralSourceToTargetCoverage10mm);
    item.insert(QStringLiteral("structural_target_to_source_coverage_3mm"), diagnostic.structuralTargetToSourceCoverage3mm);
    item.insert(QStringLiteral("structural_target_to_source_coverage_5mm"), diagnostic.structuralTargetToSourceCoverage5mm);
    item.insert(QStringLiteral("structural_target_to_source_coverage_10mm"), diagnostic.structuralTargetToSourceCoverage10mm);
    item.insert(QStringLiteral("structural_bidirectional_coverage_3mm"), diagnostic.structuralBidirectionalCoverage3mm);
    item.insert(QStringLiteral("structural_validation_passed"), diagnostic.structuralValidationPassed);
    item.insert(QStringLiteral("structural_validation_reason"), diagnostic.structuralValidationReason);
    item.insert(QStringLiteral("structural_icp_used"), diagnostic.structuralIcpUsed);
    item.insert(QStringLiteral("structural_icp_reason"), diagnostic.structuralIcpReason);
    item.insert(QStringLiteral("tangent_coarse_alignment_attempted"), diagnostic.tangentCoarseAlignmentAttempted);
    item.insert(QStringLiteral("tangent_coarse_alignment_applied"), diagnostic.tangentCoarseAlignmentApplied);
    item.insert(QStringLiteral("tangent_coverage_before"), diagnostic.tangentCoverageBefore);
    item.insert(QStringLiteral("tangent_coverage_after"), diagnostic.tangentCoverageAfter);
    item.insert(QStringLiteral("tangent_coarse_xyz_mm"), QJsonArray{diagnostic.tangentCoarseX,diagnostic.tangentCoarseY,diagnostic.tangentCoarseZ});
    item.insert(QStringLiteral("tangent_coarse_alignment_reason"), diagnostic.tangentCoarseAlignmentReason);
    item.insert(QStringLiteral("plane_diagnostic_valid"), diagnostic.planeDiagnosticValid);
    item.insert(QStringLiteral("plane_normal_angle_deg"), diagnostic.planeNormalAngleDegrees);
    item.insert(QStringLiteral("source_plane_height_mm"), diagnostic.sourcePlaneHeight);
    item.insert(QStringLiteral("target_plane_height_mm"), diagnostic.targetPlaneHeight);
    item.insert(QStringLiteral("plane_offset_difference_mm"), diagnostic.planeOffsetDifference);
    item.insert(QStringLiteral("plane_prealignment_attempted"), diagnostic.planePrealignmentAttempted);
    item.insert(QStringLiteral("plane_prealignment_accepted"), diagnostic.planePrealignmentAccepted);
    item.insert(QStringLiteral("plane_prealignment_translation_mm"), diagnostic.planePrealignmentTranslation);
    item.insert(QStringLiteral("plane_prealignment_angle_deg"), diagnostic.planePrealignmentAngleDegrees);
    item.insert(QStringLiteral("plane_prealignment_xyz_mm"), QJsonArray{diagnostic.planePrealignmentX, diagnostic.planePrealignmentY, diagnostic.planePrealignmentZ});
    item.insert(QStringLiteral("plane_residual_after_prealignment_mm"), diagnostic.planeResidualAfterPrealignment);
    item.insert(QStringLiteral("plane_normal_angle_after_prealignment_deg"), diagnostic.planeNormalAngleAfterPrealignment);
    item.insert(QStringLiteral("plane_prealignment_reason"), diagnostic.planePrealignmentReason);
    item.insert(QStringLiteral("plane_identity_tracked"), diagnostic.planeIdentityTracked);
    item.insert(QStringLiteral("tracked_source_plane_height_mm"), diagnostic.trackedSourcePlaneHeight);
    item.insert(QStringLiteral("tracked_target_plane_height_mm"), diagnostic.trackedTargetPlaneHeight);
    item.insert(QStringLiteral("plane_identity_reason"), diagnostic.planeIdentityReason);
    item.insert(QStringLiteral("fitness"), diagnostic.fitness);
    item.insert(QStringLiteral("rmse_mm"), diagnostic.rmse);
    item.insert(QStringLiteral("correction_translation_mm"), diagnostic.correctionTranslation);
    item.insert(QStringLiteral("correction_angle_deg"), diagnostic.correctionAngleDegrees);
    QJsonArray levels;
    for (int index = 0; index < diagnostic.levelFitness.size(); ++index) {
        QJsonObject level;
        level.insert(QStringLiteral("voxel_mm"), options.voxelLevels.value(index));
        level.insert(QStringLiteral("max_correspondence_mm"), options.correspondenceDistances.value(index));
        level.insert(QStringLiteral("fitness"), diagnostic.levelFitness.value(index));
        level.insert(QStringLiteral("rmse_mm"), diagnostic.levelRmse.value(index));
        level.insert(QStringLiteral("correspondences"), diagnostic.levelCorrespondences.value(index));
        levels.append(level);
    }
    item.insert(QStringLiteral("levels"), levels);
    return item;
}
}

int runRegression(const QStringList &arguments)
{
    QCommandLineParser parser;
    parser.setApplicationDescription(QStringLiteral("pointcloudstitch 多帧回归诊断"));
    parser.addHelpOption();
    const QCommandLineOption regressionOption(QStringLiteral("regression"), QStringLiteral("运行多帧回归诊断"));
    const QCommandLineOption inputOption(QStringLiteral("input-dir"), QStringLiteral("ASCII PLY 目录"), QStringLiteral("path"));
    const QCommandLineOption poseOption(QStringLiteral("pose-info"), QStringLiteral("Start/End 位姿 TXT"), QStringLiteral("path"));
    const QCommandLineOption calibrationOption(QStringLiteral("calibration"), QStringLiteral("Eye-in-Hand XML"), QStringLiteral("path"));
    const QCommandLineOption reportOption(QStringLiteral("report"), QStringLiteral("输出 JSON 报告"), QStringLiteral("path"));
    const QCommandLineOption outputOption(QStringLiteral("output-dir"), QStringLiteral("转换模式输出 PLY 目录"), QStringLiteral("path"));
    const QCommandLineOption voxelOption(QStringLiteral("voxel-levels"), QStringLiteral("三个体素层级"), QStringLiteral("values"), QStringLiteral("1 0.5 0.2"));
    const QCommandLineOption distanceOption(QStringLiteral("correspondence-distances"), QStringLiteral("三个对应距离"), QStringLiteral("values"), QStringLiteral("3 1.5 0.6"));
    const QCommandLineOption transformOnlyOption(QStringLiteral("transform-only"), QStringLiteral("仅执行手眼坐标转换，跳过预对齐和 ICP"));
    parser.addOptions({regressionOption, inputOption, poseOption, calibrationOption, reportOption, outputOption, voxelOption, distanceOption, transformOnlyOption});
    parser.process(arguments);
    const QString inputDirectory = parser.value(inputOption);
    const QString posePath = parser.value(poseOption);
    const QString calibrationPath = parser.value(calibrationOption);
    const QString reportPath = parser.value(reportOption);
    const QString outputDirectory = parser.value(outputOption);
    if (inputDirectory.isEmpty() || posePath.isEmpty() || calibrationPath.isEmpty() || reportPath.isEmpty()) return 2;

    QString error;
    QMatrix4x4 calibration;
    QHash<int, PoseRecord> poses;
    if (!readCalibration(calibrationPath, &calibration, &error) || !readPoseInfo(posePath, &poses, &error)) return 2;
    pointcloud::IcpOptions options;
    options.enabled = !parser.isSet(transformOnlyOption);
    options.voxelLevels = parseLevels(parser.value(voxelOption), &error);
    options.correspondenceDistances = parseLevels(parser.value(distanceOption), &error);
    if (!error.isEmpty()) return 2;

    QDir directory(inputDirectory);
    const QStringList files = directory.entryList({QStringLiteral("*.ply")}, QDir::Files, QDir::Name);
    QVector<pointcloud::WorldCloudInput> inputs;
    QVector<PoseRecord> orderedPoses;
    const QRegularExpression scanPattern(QStringLiteral("A(\\d+)\\.ply$"), QRegularExpression::CaseInsensitiveOption);
    for (const QString &file : files) {
        const auto match = scanPattern.match(file);
        if (!match.hasMatch()) continue;
        const int scan = match.captured(1).toInt();
        if (!poses.contains(scan)) continue;
        const PoseRecord record = poses.value(scan);
        pointcloud::WorldCloudInput input;
        input.filePath = directory.absoluteFilePath(file);
        input.startBaseFromFlange = poseMatrix(record.start);
        input.endBaseFromFlange = poseMatrix(record.end);
        input.flangeFromDepth = calibration;
        inputs.push_back(input);
        orderedPoses.push_back(record);
    }

    pointcloud::WorldCloudMergeResult result;
    if (inputs.size() >= 2) result = pointcloud::mergePlyCloudsInWorld(inputs, options);
    else if (!options.enabled && inputs.size() == 1) result = pointcloud::mergePlyCloudsInWorld(inputs, options);
    else result.error = QStringLiteral("PLY 文件与位姿记录匹配后少于所需帧数");
    bool allAccepted = result.ok && result.icpDiagnostics.size() == inputs.size();
    if (options.enabled)
        for (int index = 1; index < result.icpDiagnostics.size(); ++index)
            allAccepted = allAccepted && result.icpDiagnostics[index].accepted;

    QJsonObject root;
    root.insert(QStringLiteral("schema"), QStringLiteral("pointcloudstitch-regression-v1"));
    root.insert(QStringLiteral("generated_at"), QDateTime::currentDateTime().toString(Qt::ISODateWithMs));
    root.insert(QStringLiteral("success"), allAccepted);
    root.insert(QStringLiteral("processing_mode"), options.enabled
        ?QStringLiteral("registration_only")
        :QStringLiteral("hand_eye_transform_only"));
    root.insert(QStringLiteral("registration_applied"), options.enabled&&allAccepted);
    root.insert(QStringLiteral("seam_fusion_applied"), false);
    root.insert(QStringLiteral("formal_output"), false);
    root.insert(QStringLiteral("error"), result.error);
    root.insert(QStringLiteral("diagnostics"), result.diagnostics);
    root.insert(QStringLiteral("input_directory"), QDir::toNativeSeparators(directory.absolutePath()));
    root.insert(QStringLiteral("pose_info"), QDir::toNativeSeparators(QFileInfo(posePath).absoluteFilePath()));
    root.insert(QStringLiteral("calibration"), QDir::toNativeSeparators(QFileInfo(calibrationPath).absoluteFilePath()));
    if (!outputDirectory.isEmpty()) root.insert(QStringLiteral("output_directory"), QDir::toNativeSeparators(QFileInfo(outputDirectory).absoluteFilePath()));
    QJsonArray inputArray;
    for (int index = 0; index < inputs.size(); ++index) {
        QJsonObject input;
        input.insert(QStringLiteral("scan"), orderedPoses[index].scan);
        input.insert(QStringLiteral("file"), inputs[index].filePath);
        input.insert(QStringLiteral("start"), vectorJson(orderedPoses[index].start));
        input.insert(QStringLiteral("end"), vectorJson(orderedPoses[index].end));
        inputArray.append(input);
    }
    root.insert(QStringLiteral("inputs"), inputArray);
    QJsonObject parameterObject;
    QJsonArray voxels, distances;
    for (float value : options.voxelLevels) voxels.append(value);
    for (float value : options.correspondenceDistances) distances.append(value);
    parameterObject.insert(QStringLiteral("voxel_levels_mm"), voxels);
    parameterObject.insert(QStringLiteral("correspondence_distances_mm"), distances);
    parameterObject.insert(QStringLiteral("icp_enabled"), options.enabled);
    parameterObject.insert(QStringLiteral("structural_validation_enabled"), options.structuralValidationEnabled);
    parameterObject.insert(QStringLiteral("structural_plane_exclusion_mm"), options.structuralPlaneExclusionMm);
    parameterObject.insert(QStringLiteral("minimum_degenerate_structural_coverage_3mm"), options.minimumDegenerateStructuralCoverage3mm);
    parameterObject.insert(QStringLiteral("minimum_structural_points"), options.minimumStructuralPoints);
    parameterObject.insert(QStringLiteral("structural_icp_enabled"), options.structuralIcpEnabled);
    parameterObject.insert(QStringLiteral("support_plane_sample_stride"), options.supportPlaneSampleStride);
    parameterObject.insert(QStringLiteral("tangent_coarse_alignment_enabled"), options.tangentCoarseAlignmentEnabled);
    parameterObject.insert(QStringLiteral("tangent_coarse_search_radius_mm"), options.tangentCoarseSearchRadiusMm);
    parameterObject.insert(QStringLiteral("tangent_coarse_step_mm"), options.tangentCoarseStepMm);
    parameterObject.insert(QStringLiteral("tangent_coarse_refine_step_mm"), options.tangentCoarseRefineStepMm);
    parameterObject.insert(QStringLiteral("tangent_coarse_minimum_coverage_gain"), options.tangentCoarseMinimumCoverageGain);
    parameterObject.insert(QStringLiteral("sample_stride"), options.sampleStride);
    parameterObject.insert(QStringLiteral("overlap_margin_mm"), options.overlapMargin);
    parameterObject.insert(QStringLiteral("plane_prealignment_enabled"), options.planePrealignmentEnabled);
    parameterObject.insert(QStringLiteral("maximum_plane_prealignment_translation_mm"), options.maximumPlanePrealignmentTranslation);
    parameterObject.insert(QStringLiteral("maximum_plane_prealignment_angle_deg"), options.maximumPlanePrealignmentAngleDegrees);
    parameterObject.insert(QStringLiteral("plane_identity_tracking_enabled"), options.planeIdentityTrackingEnabled);
    parameterObject.insert(QStringLiteral("plane_identity_height_tolerance_mm"), options.planeIdentityHeightToleranceMm);
    parameterObject.insert(QStringLiteral("plane_fit_height_band_mm"), options.planeFitHeightBandMm);
    parameterObject.insert(QStringLiteral("plane_fit_inlier_distance_mm"), options.planeFitInlierDistanceMm);
    parameterObject.insert(QStringLiteral("plane_fit_iterations"), options.planeFitIterations);
    parameterObject.insert(QStringLiteral("plane_identity_tracking_valid"), result.planeIdentityTrackingValid);
    parameterObject.insert(QStringLiteral("plane_identity_consensus_height_mm"), result.planeIdentityConsensusHeight);
    parameterObject.insert(QStringLiteral("plane_identity_diagnostics"), result.planeIdentityDiagnostics);
    QJsonArray trackedPlaneHeights;
    for(float height:result.trackedPlaneHeights)trackedPlaneHeights.append(height);
    parameterObject.insert(QStringLiteral("tracked_plane_heights_mm"),trackedPlaneHeights);
    parameterObject.insert(QStringLiteral("maximum_correction_translation_mm"), options.maximumCorrectionTranslation);
    parameterObject.insert(QStringLiteral("maximum_correction_angle_deg"), options.maximumCorrectionAngleDegrees);
    root.insert(QStringLiteral("parameters"), parameterObject);
    QJsonArray pairs;
    for (int index = 1; index < result.icpDiagnostics.size(); ++index)
        pairs.append(diagnosticJson(result.icpDiagnostics[index], options));
    root.insert(QStringLiteral("adjacent_pairs"), pairs);

    if (!outputDirectory.isEmpty()) {
        QDir output(outputDirectory);
        if (!output.exists() && !QDir().mkpath(outputDirectory)) return 3;
        QString outputError;
        QJsonArray preFiles,postFiles;
        if(options.enabled){
            for(int index=0;index<result.diagnosticPreIcpFrames.size();++index){
                const QString prePath=output.filePath(QStringLiteral("diagnostic_pre_icp_frame_%1.ply").arg(index+1,2,10,QChar('0')));
                const QString postPath=output.filePath(QStringLiteral("diagnostic_post_icp_frame_%1.ply").arg(index+1,2,10,QChar('0')));
                if(!writeAsciiPly(prePath,result.diagnosticPreIcpFrames[index],&outputError)
                    ||!writeAsciiPly(postPath,result.diagnosticPostIcpFrames.value(index),&outputError))return 3;
                preFiles.append(QDir::toNativeSeparators(prePath));postFiles.append(QDir::toNativeSeparators(postPath));
            }
        }
        root.insert(QStringLiteral("diagnostic_pre_icp_frame_files"),preFiles);
        root.insert(QStringLiteral("diagnostic_post_icp_frame_files"),postFiles);
        if(allAccepted&&!result.points.isEmpty()){
            const QString mergedPath = output.filePath(options.enabled
                ? QStringLiteral("regression_registered_robot_base.ply")
                : QStringLiteral("transformed_robot_base.ply"));
            if (!writeAsciiPly(mergedPath, result.points, &outputError)) return 3;
            QVector<pointcloud::Point3D> preview;
            preview.reserve((result.points.size() + 15) / 16);
            for (int index = 0; index < result.points.size(); index += 16)preview.push_back(result.points.at(index));
            const QString previewPath = output.filePath(options.enabled
                ? QStringLiteral("regression_registered_robot_base_preview.ply")
                : QStringLiteral("transformed_robot_base_preview.ply"));
            if (!writeAsciiPly(previewPath, preview, &outputError)) return 3;
            root.insert(QStringLiteral("diagnostic_registered_output"), QDir::toNativeSeparators(mergedPath));
            root.insert(QStringLiteral("diagnostic_registered_preview"), QDir::toNativeSeparators(previewPath));
        }
    }

    QDir().mkpath(QFileInfo(reportPath).absolutePath());
    QSaveFile report(reportPath);
    if (!report.open(QIODevice::WriteOnly)
        || report.write(QJsonDocument(root).toJson(QJsonDocument::Indented)) < 0
        || !report.commit()) return 3;
    return allAccepted ? 0 : 1;
}
