#include "stitchingwindow.h"
#include "handeye_transform.h"
#include "ui_stitchingwindow.h"

#include <QDateTime>
#include <QDataStream>
#include <QDir>
#include <QDirIterator>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QHeaderView>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QMessageBox>
#include <QRegularExpression>
#include <QSaveFile>
#include <QSet>
#include <QStandardPaths>
#include <QTableWidgetItem>
#include <QTextStream>
#include <QtConcurrent/QtConcurrentRun>
#include <QtMath>

#include <algorithm>
#include <cmath>
#include <limits>
#include <unordered_map>

namespace {

bool writeBinaryPly(const QString &path, const QVector<pointcloud::Point3D> &points,
                    QString *error)
{
    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly)) {
        if (error) *error = QObject::tr("无法创建输出文件：%1").arg(path);
        return false;
    }
    const QByteArray header = QStringLiteral(
        "ply\nformat binary_little_endian 1.0\n"
        "comment generated by pointcloudstitch\n"
        "element vertex %1\n"
        "property float x\nproperty float y\nproperty float z\n"
        "end_header\n").arg(points.size()).toLatin1();
    if (file.write(header) != header.size()) {
        if (error) *error = QObject::tr("写入 PLY 头失败：%1").arg(path);
        return false;
    }
    QDataStream stream(&file);
    stream.setByteOrder(QDataStream::LittleEndian);
    stream.setFloatingPointPrecision(QDataStream::SinglePrecision);
    for (const pointcloud::Point3D &point : points)
        stream << point.x << point.y << point.z;
    if (stream.status() != QDataStream::Ok || !file.commit()) {
        if (error) *error = QObject::tr("写入 PLY 数据失败：%1").arg(path);
        return false;
    }
    return true;
}

bool writePointMapping(const QString &path, const pointcloud::WorldCloudMergeResult &merge,
                       QString *error)
{
    if (merge.points.size() != merge.cloudIds.size()
        || merge.points.size() != merge.sourceIndices.size()
        || merge.points.size() != merge.scanRatios.size()) {
        if (error) *error = QObject::tr("点云来源映射长度不一致");
        return false;
    }
    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly)) {
        if (error) *error = QObject::tr("无法创建点云来源映射：%1").arg(path);
        return false;
    }
    QDataStream stream(&file);
    stream.setByteOrder(QDataStream::LittleEndian);
    stream.setFloatingPointPrecision(QDataStream::SinglePrecision);
    stream << quint32(0x314D4350) << quint32(1) << quint64(merge.points.size());
    for (qsizetype i = 0; i < merge.points.size(); ++i)
        stream << qint32(merge.cloudIds[i]) << qint64(merge.sourceIndices[i])
               << merge.scanRatios[i];
    if (stream.status() != QDataStream::Ok || !file.commit()) {
        if (error) *error = QObject::tr("写入点云来源映射失败：%1").arg(path);
        return false;
    }
    return true;
}

QVector<pointcloud::Point3D> deterministicPreview(const QVector<pointcloud::Point3D> &points,
                                                   double keepRatio)
{
    keepRatio = qBound(0.01, keepRatio, 1.0);
    if (keepRatio >= 0.999) return points;
    const quint64 threshold = quint64(keepRatio
        * static_cast<long double>(std::numeric_limits<quint64>::max()));
    QVector<pointcloud::Point3D> preview;
    preview.reserve(qsizetype(double(points.size()) * keepRatio) + 1);
    for (const pointcloud::Point3D &point : points) {
        const qint64 x = qint64(std::floor(double(point.x) / 0.2));
        const qint64 y = qint64(std::floor(double(point.y) / 0.2));
        const qint64 z = qint64(std::floor(double(point.z) / 0.2));
        quint64 value = quint64(x) * 73856093ULL
            ^ quint64(y) * 19349663ULL
            ^ quint64(z) * 83492791ULL;
        value ^= value >> 30;
        value *= 0xBF58476D1CE4E5B9ULL;
        value ^= value >> 27;
        value *= 0x94D049BB133111EBULL;
        value ^= value >> 31;
        if (value <= threshold) preview.push_back(point);
    }
    return preview;
}

bool writeReport(const QString &path, const StitchTaskResult &result, QString *error)
{
    QJsonObject root;
    root.insert(QStringLiteral("schema"), QStringLiteral("pointcloudstitch-report-v2"));
    root.insert(QStringLiteral("schema_version"), QStringLiteral("1.0.0"));
    root.insert(QStringLiteral("coordinate_contract"), QStringLiteral("camera -> flange -> robot_base"));
    root.insert(QStringLiteral("length_unit"), QStringLiteral("mm"));
    root.insert(QStringLiteral("angle_unit"), QStringLiteral("deg"));
    root.insert(QStringLiteral("generated_at"), QDateTime::currentDateTime().toString(Qt::ISODateWithMs));
    root.insert(QStringLiteral("success"), result.ok);
    root.insert(QStringLiteral("processing_mode"), result.transformOnly
        ? QStringLiteral("hand_eye_transform_only")
        : QStringLiteral("registration_and_fusion"));
    root.insert(QStringLiteral("registration_all_accepted"), result.registrationAccepted);
    root.insert(QStringLiteral("multi_frame_consistent"), result.multiFrameConsistent);
    root.insert(QStringLiteral("diagnostics"), result.merge.diagnostics);
    QJsonObject registration;
    registration.insert(QStringLiteral("enabled"), result.icpOptions.enabled);
    registration.insert(QStringLiteral("icp_metric"), QStringLiteral("point_to_plane"));
    registration.insert(QStringLiteral("normal_estimation"), QStringLiteral("local_pca"));
    registration.insert(QStringLiteral("reference_scope"), QStringLiteral("adjacent_overlap"));
    QJsonArray voxelLevels;
    for (float level : result.icpOptions.voxelLevels) voxelLevels.append(level);
    registration.insert(QStringLiteral("voxel_levels_mm"), voxelLevels);
    QJsonArray correspondenceDistances;
    for (float distance : result.icpOptions.correspondenceDistances)
        correspondenceDistances.append(distance);
    registration.insert(QStringLiteral("correspondence_distances_mm"), correspondenceDistances);
    registration.insert(QStringLiteral("sample_stride"), result.icpOptions.sampleStride);
    registration.insert(QStringLiteral("overlap_margin_mm"), result.icpOptions.overlapMargin);
    registration.insert(QStringLiteral("plane_prealignment_enabled"), result.icpOptions.planePrealignmentEnabled);
    registration.insert(QStringLiteral("maximum_plane_prealignment_translation_mm"), result.icpOptions.maximumPlanePrealignmentTranslation);
    registration.insert(QStringLiteral("maximum_plane_prealignment_angle_deg"), result.icpOptions.maximumPlanePrealignmentAngleDegrees);
    registration.insert(QStringLiteral("maximum_correction_translation_mm"),
                        result.icpOptions.maximumCorrectionTranslation);
    registration.insert(QStringLiteral("maximum_correction_angle_deg"),
                        result.icpOptions.maximumCorrectionAngleDegrees);
    QJsonArray finalCorrections;
    for (const QMatrix4x4 &matrix : result.merge.registrationCorrections) {
        QJsonArray values;
        for (int row = 0; row < 4; ++row)
            for (int column = 0; column < 4; ++column)
                values.append(matrix(row, column));
        finalCorrections.append(values);
    }
    registration.insert(QStringLiteral("final_corrections_row_major"), finalCorrections);
    root.insert(QStringLiteral("registration"), registration);
    QJsonObject output;
    output.insert(QStringLiteral("merged_file"), result.mergedFile);
    output.insert(QStringLiteral("merged_points"), double(result.merge.points.size()));
    output.insert(QStringLiteral("points_before_output_downsample"), double(result.pointsBeforeOutputDownsample));
    output.insert(QStringLiteral("output_downsample_voxel_mm"), result.outputDownsampleVoxelSize);
    // Formal output keeps every real point. A zero budget explicitly means
    // that no post-registration point-count cap or output voxel is applied.
    output.insert(QStringLiteral("output_point_budget"), 0.0);
    output.insert(QStringLiteral("points_before_cross_cloud_fusion"),
                  double(result.merge.pointsBeforeCrossCloudFusion));
    output.insert(QStringLiteral("cross_cloud_duplicates"),
                  double(result.merge.crossCloudDuplicateCount));
    output.insert(QStringLiteral("fusion_voxel_mm"), result.merge.crossCloudFusionVoxelSize);
    output.insert(QStringLiteral("preview_file"), result.previewFile);
    output.insert(QStringLiteral("preview_points"), double(result.previewCount));
    output.insert(QStringLiteral("point_mapping_file"), result.mappingFile);
    output.insert(QStringLiteral("point_mapping_format"), QStringLiteral("PCVMAP1: cloud_id(int32), source_index(int64), scan_ratio(float32)"));
    QJsonArray sourceFiles;
    for (const QString &file : result.retainedSourceFiles) sourceFiles.append(file);
    output.insert(QStringLiteral("retained_source_files"), sourceFiles);
    output.insert(QStringLiteral("full_resolution_source_files"), sourceFiles);
    root.insert(QStringLiteral("output"), output);

    QJsonArray frames;
    const auto matrixJson = [](const QMatrix4x4 &matrix) {
        QJsonArray rows;
        for (int row = 0; row < 4; ++row) {
            QJsonArray values;
            for (int column = 0; column < 4; ++column) values.append(matrix(row, column));
            rows.append(values);
        }
        return rows;
    };
    for (const auto &frame : result.merge.frameMetadata) {
        QJsonObject item;
        item.insert(QStringLiteral("source_file"), frame.sourceFile);
        item.insert(QStringLiteral("source_frame"), QStringLiteral("camera"));
        item.insert(QStringLiteral("target_frame"), QStringLiteral("robot_base"));
        item.insert(QStringLiteral("start_base_from_flange"), matrixJson(frame.startBaseFromFlange));
        item.insert(QStringLiteral("end_base_from_flange"), matrixJson(frame.endBaseFromFlange));
        item.insert(QStringLiteral("flange_from_depth"), matrixJson(frame.flangeFromDepth));
        item.insert(QStringLiteral("declared_points"), double(frame.declaredCount));
        item.insert(QStringLiteral("converted_points"), double(frame.convertedCount));
        item.insert(QStringLiteral("rejected_invalid"), double(frame.rejectedInvalid));
        item.insert(QStringLiteral("rejected_range"), double(frame.rejectedRange));
        item.insert(QStringLiteral("input_y_min"), frame.inputYMinimum);
        item.insert(QStringLiteral("input_y_max"), frame.inputYMaximum);
        item.insert(QStringLiteral("signed_travel"), frame.signedTravel);
        item.insert(QStringLiteral("dominant_travel_axis"), frame.dominantTravelAxis);
        frames.append(item);
    }
    root.insert(QStringLiteral("frames"), frames);
    QJsonObject mapping;
    mapping.insert(QStringLiteral("point_count"), double(result.merge.points.size()));
    mapping.insert(QStringLiteral("cloud_id_semantics"), QStringLiteral("frames array index"));
    mapping.insert(QStringLiteral("source_index_semantics"), QStringLiteral("vertex index after source PLY parsing"));
    mapping.insert(QStringLiteral("scan_ratio_semantics"), QStringLiteral("PLY.Y / signed_travel, clamped to [0,1]"));
    root.insert(QStringLiteral("point_mapping"), mapping);

    QJsonArray icpArray;
    for (const pointcloud::IcpDiagnostics &diagnostic : result.merge.icpDiagnostics) {
        QJsonObject item;
        item.insert(QStringLiteral("file"), diagnostic.filePath);
        item.insert(QStringLiteral("attempted"), diagnostic.attempted);
        item.insert(QStringLiteral("accepted"), diagnostic.accepted);
        item.insert(QStringLiteral("target_cloud_index"), diagnostic.targetCloudIndex);
        item.insert(QStringLiteral("source_cloud_index"), diagnostic.sourceCloudIndex);
        item.insert(QStringLiteral("source_crop_points"), diagnostic.sourceCropCount);
        item.insert(QStringLiteral("target_crop_points"), diagnostic.targetCropCount);
        item.insert(QStringLiteral("actual_overlap_source_points"), diagnostic.actualOverlapSourceCount);
        item.insert(QStringLiteral("actual_overlap_target_points"), diagnostic.actualOverlapTargetCount);
        item.insert(QStringLiteral("overlap_minimum_retention"), diagnostic.minimumOverlapRetention);
        item.insert(QStringLiteral("overlap_constrained_step_reductions"), diagnostic.overlapConstrainedStepReductions);
        item.insert(QStringLiteral("degenerate"), diagnostic.degenerate);
        item.insert(QStringLiteral("observable_dof"), diagnostic.observableDof);
        item.insert(QStringLiteral("hessian_condition_ratio"), diagnostic.conditionRatio);
        item.insert(QStringLiteral("degenerate_projected_iterations"), diagnostic.projectedIterations);
        item.insert(QStringLiteral("projected_overlap_width_mm"), diagnostic.projectedOverlapWidth);
        item.insert(QStringLiteral("nearest_distance_p50_mm"), diagnostic.nearestDistanceP50);
        item.insert(QStringLiteral("nearest_distance_p90_mm"), diagnostic.nearestDistanceP90);
        item.insert(QStringLiteral("nearest_distance_p95_mm"), diagnostic.nearestDistanceP95);
        item.insert(QStringLiteral("coverage_within_3mm"), diagnostic.coverageWithin3mm);
        item.insert(QStringLiteral("coverage_within_5mm"), diagnostic.coverageWithin5mm);
        item.insert(QStringLiteral("coverage_within_10mm"), diagnostic.coverageWithin10mm);
        item.insert(QStringLiteral("nearest_distance_p50_after_prealignment_mm"), diagnostic.nearestDistanceP50AfterPrealignment);
        item.insert(QStringLiteral("nearest_distance_p90_after_prealignment_mm"), diagnostic.nearestDistanceP90AfterPrealignment);
        item.insert(QStringLiteral("nearest_distance_p95_after_prealignment_mm"), diagnostic.nearestDistanceP95AfterPrealignment);
        item.insert(QStringLiteral("coverage_within_3mm_after_prealignment"), diagnostic.coverageWithin3mmAfterPrealignment);
        item.insert(QStringLiteral("coverage_within_5mm_after_prealignment"), diagnostic.coverageWithin5mmAfterPrealignment);
        item.insert(QStringLiteral("coverage_within_10mm_after_prealignment"), diagnostic.coverageWithin10mmAfterPrealignment);
        item.insert(QStringLiteral("plane_diagnostic_valid"), diagnostic.planeDiagnosticValid);
        item.insert(QStringLiteral("plane_normal_angle_deg"), diagnostic.planeNormalAngleDegrees);
        item.insert(QStringLiteral("source_plane_height_mm"), diagnostic.sourcePlaneHeight);
        item.insert(QStringLiteral("target_plane_height_mm"), diagnostic.targetPlaneHeight);
        item.insert(QStringLiteral("plane_offset_difference_mm"), diagnostic.planeOffsetDifference);
        item.insert(QStringLiteral("plane_prealignment_attempted"), diagnostic.planePrealignmentAttempted);
        item.insert(QStringLiteral("plane_prealignment_accepted"), diagnostic.planePrealignmentAccepted);
        item.insert(QStringLiteral("plane_prealignment_translation_mm"), diagnostic.planePrealignmentTranslation);
        item.insert(QStringLiteral("plane_prealignment_angle_deg"), diagnostic.planePrealignmentAngleDegrees);
        item.insert(QStringLiteral("plane_prealignment_xyz_mm"), QJsonArray{diagnostic.planePrealignmentX, diagnostic.planePrealignmentY, diagnostic.planePrealignmentZ});
        item.insert(QStringLiteral("plane_residual_after_prealignment_mm"), diagnostic.planeResidualAfterPrealignment);
        item.insert(QStringLiteral("plane_normal_angle_after_prealignment_deg"), diagnostic.planeNormalAngleAfterPrealignment);
        item.insert(QStringLiteral("plane_prealignment_reason"), diagnostic.planePrealignmentReason);
        item.insert(QStringLiteral("fitness"), diagnostic.fitness);
        item.insert(QStringLiteral("rmse_mm"), diagnostic.rmse);
        item.insert(QStringLiteral("xy_rmse_mm"), diagnostic.xyRmse);
        item.insert(QStringLiteral("z_rmse_mm"), diagnostic.zRmse);
        item.insert(QStringLiteral("correction_translation_mm"), diagnostic.correctionTranslation);
        item.insert(QStringLiteral("correction_angle_deg"), diagnostic.correctionAngleDegrees);
        item.insert(QStringLiteral("reason"), diagnostic.reason);
        item.insert(QStringLiteral("correspondences"), diagnostic.correspondences);
        item.insert(QStringLiteral("unique_reference_ratio"), diagnostic.uniqueReferenceRatio);
        item.insert(QStringLiteral("correction_xyz_mm"), QJsonArray{diagnostic.correctionX,diagnostic.correctionY,diagnostic.correctionZ});
        QJsonArray levels;
        for (int level = 0; level < diagnostic.levelFitness.size(); ++level) {
            QJsonObject levelItem;
            levelItem.insert(QStringLiteral("voxel_mm"),
                             result.icpOptions.voxelLevels.value(level));
            levelItem.insert(QStringLiteral("max_correspondence_mm"),
                             result.icpOptions.correspondenceDistances.value(level));
            levelItem.insert(QStringLiteral("fitness"), diagnostic.levelFitness.value(level));
            levelItem.insert(QStringLiteral("inlier_rmse_mm"), diagnostic.levelRmse.value(level));
            levelItem.insert(QStringLiteral("correspondences"),
                             diagnostic.levelCorrespondences.value(level));
            levels.append(levelItem);
        }
        item.insert(QStringLiteral("levels"), levels);
        icpArray.append(item);
    }
    root.insert(QStringLiteral("icp"), icpArray);

    QJsonObject seam;
    seam.insert(QStringLiteral("input_points"), double(result.seamFusion.inputPoints));
    seam.insert(QStringLiteral("output_points"), double(result.seamFusion.outputPoints));
    QJsonArray seamPairs;
    for (const SeamFusionDiagnostic &diagnostic : result.seamFusion.diagnostics) {
        QJsonObject item;
        item.insert(QStringLiteral("cloud_a"), diagnostic.cloudA);
        item.insert(QStringLiteral("cloud_b"), diagnostic.cloudB);
        item.insert(QStringLiteral("applied"), diagnostic.applied);
        item.insert(QStringLiteral("seam_source"), QStringLiteral("actual_overlap_midpoint"));
        item.insert(QStringLiteral("actual_overlap_valid"), diagnostic.actualOverlapValid);
        item.insert(QStringLiteral("projected_range_a"), QJsonArray{diagnostic.projectedAMin, diagnostic.projectedAMax});
        item.insert(QStringLiteral("projected_range_b"), QJsonArray{diagnostic.projectedBMin, diagnostic.projectedBMax});
        item.insert(QStringLiteral("actual_overlap_interval"), QJsonArray{diagnostic.actualOverlapMin, diagnostic.actualOverlapMax});
        item.insert(QStringLiteral("seam_projection"), diagnostic.seamProjection);
        item.insert(QStringLiteral("band_points"), double(diagnostic.bandPoints));
        item.insert(QStringLiteral("band_points_a"), double(diagnostic.bandPointsA));
        item.insert(QStringLiteral("band_points_b"), double(diagnostic.bandPointsB));
        item.insert(QStringLiteral("mutual_pairs"), double(diagnostic.mutualPairs));
        item.insert(QStringLiteral("interpolated_points"), double(diagnostic.interpolatedPoints));
        item.insert(QStringLiteral("unmatched_discarded"), double(diagnostic.unmatchedDiscarded));
        item.insert(QStringLiteral("unmatched_preserved"), double(diagnostic.unmatchedPreserved));
        item.insert(QStringLiteral("decision_cells"), double(diagnostic.decisionCells));
        item.insert(QStringLiteral("core_points_at_seam"), double(diagnostic.corePoints));
        item.insert(QStringLiteral("reason"), diagnostic.reason);
        seamPairs.append(item);
    }
    seam.insert(QStringLiteral("pairs"), seamPairs);
    root.insert(QStringLiteral("seam_fusion"), seam);

    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly)
        || file.write(QJsonDocument(root).toJson(QJsonDocument::Indented)) < 0
        || !file.commit()) {
        if (error) *error = QObject::tr("无法写入报告：%1").arg(path);
        return false;
    }
    return true;
}

StitchTaskResult runStitching(const QVector<pointcloud::WorldCloudInput> &inputs,
                              const pointcloud::IcpOptions &icp,
                              const SeamFusionOptions &seamOptions,
                              const QString &outputDirectory,
                              double previewRatio,
                              bool writeSources,
                              const std::shared_ptr<std::atomic_bool> &cancelRequested,
                              const std::function<void(int, const QString &)> &progress)
{
    const auto reportProgress = [&progress](int value, const QString &message) {
        if (progress) progress(qBound(0, value, 100), message);
    };
    StitchTaskResult result;
    result.outputDirectory = outputDirectory;
    result.icpOptions = icp;
    result.transformOnly = !icp.enabled;
    pointcloud::IcpOptions runtimeIcp = icp;
    runtimeIcp.isCancelled = [cancelRequested]() {
        return cancelRequested && cancelRequested->load();
    };
    result.merge = pointcloud::mergePlyCloudsInWorld(inputs, runtimeIcp,
        [&reportProgress](float value, const QString &message) {
            reportProgress(qRound(value * 78.0f), message);
        });
    if (!result.merge.ok) {
        if (result.merge.cancelled) {
            result.cancelled = true;
            return result;
        }
        result.error = result.merge.error.isEmpty()
            ? (result.transformOnly ? QObject::tr("点云手眼坐标转换失败")
                                    : QObject::tr("点云世界坐标转换或配准失败"))
            : result.merge.error;
        return result;
    }
    result.registrationAccepted = true;
    result.multiFrameConsistent = true;
    if (icp.enabled) {
        for (int index = 1; index < result.merge.icpDiagnostics.size(); ++index) {
            const auto&diagnostic=result.merge.icpDiagnostics[index];
            if (!diagnostic.accepted) {
                result.registrationAccepted = false;
            }
        }
    }
    result.multiFrameConsistent = result.registrationAccepted;
    QDir directory(outputDirectory);
    reportProgress(79, QObject::tr("正在准备输出目录"));
    if (!directory.exists() && !QDir().mkpath(outputDirectory)) {
        result.error = QObject::tr("无法创建输出目录：%1").arg(outputDirectory);
        return result;
    }
    if (writeSources) {
        for (int cloudId = 0; cloudId < inputs.size(); ++cloudId) {
            QVector<pointcloud::Point3D> sourcePoints;
            bool correctionInvertible = false;
            const QMatrix4x4 inverseCorrection = result.merge.registrationCorrections
                .value(cloudId, QMatrix4x4()).inverted(&correctionInvertible);
            if (!correctionInvertible) {
                result.error = QObject::tr("第 %1 帧坐标修正矩阵不可逆").arg(cloudId + 1);
                return result;
            }
            for (qsizetype index = 0; index < result.merge.points.size(); ++index)
                if (result.merge.cloudIds.value(index, -1) == cloudId) {
                    pointcloud::Point3D point = result.merge.points[index];
                    const QVector3D base = inverseCorrection.map(
                        QVector3D(point.x, point.y, point.z));
                    point.x = base.x(); point.y = base.y(); point.z = base.z();
                    sourcePoints.push_back(point);
                }
            const QString base = QFileInfo(inputs[cloudId].filePath).completeBaseName();
            const QString path = directory.filePath(QStringLiteral("%1_%2_robot_base.ply")
                                                        .arg(cloudId + 1).arg(base));
            reportProgress(79, QObject::tr("正在写入全分辨率来源点云 %1/%2")
                .arg(cloudId + 1).arg(inputs.size()));
            if (!writeBinaryPly(path, sourcePoints, &result.error)) return result;
            result.retainedSourceFiles.push_back(path);
        }
    }
    reportProgress(79, result.transformOnly
        ? QObject::tr("仅坐标转换模式，跳过配准与接缝融合")
        : (result.registrationAccepted
            ? QObject::tr("正在按真实重叠区执行接缝融合")
            : QObject::tr("配准失败，跳过正式接缝融合")));
    if (!result.transformOnly && result.registrationAccepted)
        result.seamFusion = applyTrajectorySeamFusion(&result.merge, inputs, seamOptions);
    else {
        result.seamFusion.inputPoints = result.merge.points.size();
        result.seamFusion.outputPoints = result.merge.points.size();
    }
    for (const SeamFusionDiagnostic &diagnostic : result.seamFusion.diagnostics) {
        result.merge.diagnostics += QStringLiteral(
            "Seam %1-%2: ranges=[%3,%4]/[%5,%6], overlap=[%7,%8], seam=%9, band=%10/%11, mutual=%12, interpolated=%13, unmatched preserved=%14, cells=%15, %16\n")
            .arg(diagnostic.cloudA + 1).arg(diagnostic.cloudB + 1)
            .arg(diagnostic.projectedAMin).arg(diagnostic.projectedAMax)
            .arg(diagnostic.projectedBMin).arg(diagnostic.projectedBMax)
            .arg(diagnostic.actualOverlapMin).arg(diagnostic.actualOverlapMax)
            .arg(diagnostic.seamProjection).arg(diagnostic.bandPointsA).arg(diagnostic.bandPointsB)
            .arg(diagnostic.mutualPairs).arg(diagnostic.interpolatedPoints)
            .arg(diagnostic.unmatchedPreserved).arg(diagnostic.decisionCells).arg(diagnostic.reason);
    }
    if (cancelRequested && cancelRequested->load()) {
        result.cancelled = true;
        return result;
    }

    result.pointsBeforeOutputDownsample=result.merge.points.size();
    result.outputDownsampleVoxelSize=0.0f;
    result.merge.diagnostics+=QStringLiteral(
        "Output downsample disabled for formal result: points=%1, all real points retained\n")
        .arg(result.merge.points.size());

    reportProgress(85, QObject::tr("正在准备输出目录"));
    result.mergedFile = directory.filePath(result.transformOnly
        ? QStringLiteral("transformed_robot_base.ply")
        : (result.registrationAccepted
            ? QStringLiteral("stitched_robot_base.ply")
            : QStringLiteral("diagnostic_unregistered_robot_base.ply")));
    reportProgress(87, result.transformOnly
        ? QObject::tr("正在写入手眼转换后的机器人基坐标点云")
        : (result.registrationAccepted
            ? QObject::tr("正在写入机器人基坐标合并点云")
            : QObject::tr("配准未全部通过，正在写入诊断点云")));
    if (!writeBinaryPly(result.mergedFile, result.merge.points, &result.error)) return result;

    result.mappingFile = result.mergedFile;
    result.mappingFile.replace(QRegularExpression(QStringLiteral("\\.ply$")),
                               QStringLiteral(".pcvmap"));
    if (!writePointMapping(result.mappingFile, result.merge, &result.error)) return result;

    if (cancelRequested && cancelRequested->load()) {
        result.cancelled = true;
        return result;
    }
    const QVector<pointcloud::Point3D> preview = deterministicPreview(result.merge.points, previewRatio);
    result.previewCount = preview.size();
    result.previewFile = directory.filePath(result.transformOnly
        ? QStringLiteral("transformed_robot_base_preview.ply")
        : QStringLiteral("stitched_robot_base_preview.ply"));
    reportProgress(92, QObject::tr("正在写入预览点云"));
    if (!writeBinaryPly(result.previewFile, preview, &result.error)) return result;

    result.reportFile = directory.filePath(result.transformOnly
        ? QStringLiteral("coordinate_transform_report.json")
        : QStringLiteral("stitching_report.json"));
    result.ok = result.transformOnly || result.registrationAccepted;
    reportProgress(99, result.transformOnly
        ? QObject::tr("正在写入坐标转换报告")
        : QObject::tr("正在写入配准报告"));
    if (!writeReport(result.reportFile, result, &result.error)) result.ok = false;
    if (result.transformOnly && result.ok) {
        reportProgress(100, QObject::tr("手眼坐标转换和全部输出完成"));
    } else if (result.registrationAccepted && result.ok) {
        reportProgress(100, QObject::tr("点云配准和全部输出完成"));
    } else if (!result.registrationAccepted) {
        result.error = QObject::tr("至少一组相邻点云未通过参考 ICP 流程；未生成正式合并文件。诊断点云：%1\n报告：%2")
            .arg(result.mergedFile, result.reportFile);
        reportProgress(100, QObject::tr("配准失败，诊断文件已生成"));
    }
    return result;
}

QString numericText(double value)
{
    return QString::number(value, 'g', 12);
}

QString poseText(const QVector<double> &pose)
{
    QStringList values;
    values.reserve(pose.size());
    for (double value : pose) values.push_back(numericText(value));
    return values.join(QLatin1Char(' '));
}

bool parsePoseText(const QString &text, QVector<double> *pose)
{
    if (!pose) return false;
    pose->clear();
    const QStringList parts = text.trimmed().split(
        QRegularExpression(QStringLiteral("[\\s,，]+")), Qt::SkipEmptyParts);
    if (parts.size() != 6) return false;
    pose->reserve(6);
    for (const QString &part : parts) {
        bool ok = false;
        const double value = part.toDouble(&ok);
        if (!ok || !std::isfinite(value)) {
            pose->clear();
            return false;
        }
        pose->push_back(value);
    }
    return true;
}

} // namespace

StitchingWindow::StitchingWindow(QWidget *parent)
    : QMainWindow(parent), ui(new Ui::StitchingWindow)
{
    ui->setupUi(this);
    ui->tbl_scans->horizontalHeader()->setSectionResizeMode(0, QHeaderView::Stretch);
    ui->tbl_scans->horizontalHeader()->setSectionResizeMode(1, QHeaderView::Stretch);
    ui->tbl_scans->horizontalHeader()->setSectionResizeMode(2, QHeaderView::Stretch);
    ui->tbl_scans->setEditTriggers(QAbstractItemView::DoubleClicked
        | QAbstractItemView::SelectedClicked | QAbstractItemView::EditKeyPressed);

    connect(ui->btn_browse_calibration, &QPushButton::clicked, this, &StitchingWindow::browseCalibration);
    connect(ui->btn_browse_output, &QPushButton::clicked, this, &StitchingWindow::browseOutputDirectory);
    connect(ui->btn_add_files, &QPushButton::clicked, this, &StitchingWindow::addPlyFiles);
    connect(ui->btn_add_folder, &QPushButton::clicked, this, &StitchingWindow::addPlyFolder);
    connect(ui->btn_remove_rows, &QPushButton::clicked, this, &StitchingWindow::removeSelectedRows);
    connect(ui->btn_clear_files, &QPushButton::clicked, this, &StitchingWindow::clearFiles);
    connect(ui->btn_start, &QPushButton::clicked, this, &StitchingWindow::startStitching);
    connect(ui->btn_cancel, &QPushButton::clicked, this, &StitchingWindow::cancelStitching);
    connect(ui->cb_processing_mode, &QComboBox::currentIndexChanged,
            this, [this](int) { updateProcessingModeUi(); });
    updateProcessingModeUi();
    statusBar()->showMessage(tr("添加三个 ASCII PLY，并填写对应扫描 Start/End 位姿"));
}

StitchingWindow::~StitchingWindow()
{
    if (m_cancelRequested) m_cancelRequested->store(true);
    if (m_watcher && m_watcher->isRunning()) m_watcher->waitForFinished();
    delete ui;
}

void StitchingWindow::browseCalibration()
{
    const QString path = QFileDialog::getOpenFileName(this, tr("选择 Eye-in-Hand 标定 XML"),
        ui->le_calibration_path->text(), tr("XML 文件 (*.xml)"));
    if (!path.isEmpty()) ui->le_calibration_path->setText(QDir::toNativeSeparators(path));
}

void StitchingWindow::browseOutputDirectory()
{
    const QString path = QFileDialog::getExistingDirectory(this, tr("选择输出目录"),
        ui->le_output_directory->text());
    if (!path.isEmpty()) ui->le_output_directory->setText(QDir::toNativeSeparators(path));
}

void StitchingWindow::addPlyFiles()
{
    const QStringList paths = QFileDialog::getOpenFileNames(this, tr("添加 PLY 点云"), {},
                                                            tr("PLY 点云 (*.ply)"));
    for (const QString &path : paths) addPlyPath(path);
}

void StitchingWindow::addPlyFolder()
{
    const QString directory = QFileDialog::getExistingDirectory(this, tr("扫描 PLY 文件夹"));
    if (directory.isEmpty()) return;
    QStringList paths;
    QDirIterator iterator(directory, {QStringLiteral("*.ply")}, QDir::Files,
                          QDirIterator::Subdirectories);
    while (iterator.hasNext()) paths.push_back(iterator.next());
    std::sort(paths.begin(), paths.end(), [](const QString &left, const QString &right) {
        return QString::localeAwareCompare(left, right) < 0;
    });
    for (const QString &path : paths) {
        if (ui->tbl_scans->rowCount() >= 3) break;
        addPlyPath(path);
    }
    statusBar()->showMessage(tr("已按文件名顺序加入 %1/3 个 PLY")
        .arg(ui->tbl_scans->rowCount()));
}

void StitchingWindow::addPlyPath(const QString &path)
{
    if (ui->tbl_scans->rowCount() >= 3) {
        statusBar()->showMessage(tr("参考流程只接受三个 PLY"));
        return;
    }
    const QString absolute = QFileInfo(path).absoluteFilePath();
    for (int row = 0; row < ui->tbl_scans->rowCount(); ++row)
        if (QFileInfo(ui->tbl_scans->item(row, 0)->text()).absoluteFilePath() == absolute) return;

    double startX = 0.0, startY = 0.0, startZ = 0.0;
    const QRegularExpression expression(
        QStringLiteral("X(-?[0-9]+(?:\\.[0-9]+)?)Y(-?[0-9]+(?:\\.[0-9]+)?)Z(-?[0-9]+(?:\\.[0-9]+)?)"),
        QRegularExpression::CaseInsensitiveOption);
    const auto match = expression.match(QFileInfo(path).completeBaseName());
    if (match.hasMatch()) {
        startX = match.captured(1).toDouble();
        startY = match.captured(2).toDouble();
        startZ = match.captured(3).toDouble();
    }
    const QVector<double> start = {startX, startY, startZ, 0.0, 0.0, 0.0};
    const QVector<double> end = {startX, 0.0, startZ, 0.0, 0.0, 0.0};
    const int row = ui->tbl_scans->rowCount();
    ui->tbl_scans->insertRow(row);
    auto *fileItem = new QTableWidgetItem(QDir::toNativeSeparators(absolute));
    fileItem->setFlags(fileItem->flags() & ~Qt::ItemIsEditable);
    ui->tbl_scans->setItem(row, 0, fileItem);
    const QVector<QVector<double>> poses = {start, end};
    for (int column = 1; column <= 2; ++column) {
        auto *item = new QTableWidgetItem(poseText(poses[column - 1]));
        item->setToolTip(tr("按 X Y Z RX RY RZ 顺序输入 6 个数；支持空格、Tab 或逗号分隔，可整串复制粘贴"));
        ui->tbl_scans->setItem(row, column, item);
    }
    if (ui->le_output_directory->text().trimmed().isEmpty())
        ui->le_output_directory->setText(QDir(QFileInfo(path).absolutePath())
                                             .filePath(QStringLiteral("stitch_output")));
}

void StitchingWindow::removeSelectedRows()
{
    QSet<int> rowSet;
    for (const QModelIndex &index : ui->tbl_scans->selectionModel()->selectedRows()) rowSet.insert(index.row());
    QList<int> rows = rowSet.values();
    std::sort(rows.begin(), rows.end(), std::greater<int>());
    for (int row : rows) ui->tbl_scans->removeRow(row);
}

void StitchingWindow::clearFiles()
{
    ui->tbl_scans->setRowCount(0);
}

bool StitchingWindow::readCalibration(QMatrix4x4 *transform, QString *error) const
{
    const QString path = ui->le_calibration_path->text().trimmed();
    if (path.isEmpty()) {
        if (error) *error = tr("请选择 Eye-in-Hand XML");
        return false;
    }
    pointcloud::HandEyeCalibration calibration;
    if (!pointcloud::loadHandEyeCalibration(path, &calibration, error)) return false;
    *transform = calibration.flangeFromDepth;
    return true;
}

QVector<pointcloud::WorldCloudInput> StitchingWindow::collectInputs(QString *error) const
{
    QVector<pointcloud::WorldCloudInput> inputs;
    const bool transformOnly = ui->cb_processing_mode->currentIndex() == 1;
    if ((!transformOnly && ui->tbl_scans->rowCount() != 3)
        || (transformOnly && ui->tbl_scans->rowCount() < 1)) {
        if (error) *error = transformOnly
            ? tr("仅手眼坐标转换模式至少需要一个 PLY 文件")
            : tr("配准与融合模式严格要求三个 PLY 文件");
        return inputs;
    }
    QMatrix4x4 flangeFromDepth;
    if (!readCalibration(&flangeFromDepth, error)) return inputs;

    for (int row = 0; row < ui->tbl_scans->rowCount(); ++row) {
        QVector<double> start, end;
        if (!parsePoseText(ui->tbl_scans->item(row, 1)->text(), &start)) {
            if (error) *error = tr("第 %1 行 Start 必须包含 6 个有效数字：X Y Z RX RY RZ").arg(row + 1);
            return {};
        }
        if (!parsePoseText(ui->tbl_scans->item(row, 2)->text(), &end)) {
            if (error) *error = tr("第 %1 行 End 必须包含 6 个有效数字：X Y Z RX RY RZ").arg(row + 1);
            return {};
        }
        pointcloud::WorldCloudInput input;
        input.filePath = ui->tbl_scans->item(row, 0)->text();
        const pointcloud::RobotPose startPose{start[0], start[1], start[2],
                                               start[3], start[4], start[5]};
        const pointcloud::RobotPose endPose{end[0], end[1], end[2],
                                             end[3], end[4], end[5]};
        input.startBaseFromFlange = pointcloud::robotPoseToMatrix(startPose);
        input.endBaseFromFlange = pointcloud::robotPoseToMatrix(endPose);
        input.flangeFromDepth = flangeFromDepth;
        inputs.push_back(input);
    }
    return inputs;
}

pointcloud::IcpOptions StitchingWindow::collectIcpOptions(QString *error) const
{
    pointcloud::IcpOptions options;
    options.enabled = ui->cb_processing_mode->currentIndex() == 0;
    // Keep the high-precision runtime profile explicit here. This also makes
    // Qt Creator builds independent of compiler header-dependency locale.
    options.sampleStride = ui->sb_sample_stride->value();
    options.overlapMargin = float(ui->dsb_overlap_margin->value());
    const auto parseLevels = [error](const QString &text, const QString &name) {
        QVector<float> values;
        const QStringList parts = text.split(
            QRegularExpression(QStringLiteral("[\\s,，]+")), Qt::SkipEmptyParts);
        for (const QString &part : parts) {
            bool ok = false;
            const float value = part.toFloat(&ok);
            if (!ok || value <= 0.0f) {
                if (error) *error = QObject::tr("%1 必须是空格或逗号分隔的正数").arg(name);
                return QVector<float>();
            }
            values.push_back(value);
        }
        return values;
    };
    if (!options.enabled) return options;
    options.voxelLevels = parseLevels(ui->le_voxel_levels->text(), tr("体素层级"));
    if (error && !error->isEmpty()) return options;
    options.correspondenceDistances = parseLevels(
        ui->le_correspondence_distances->text(), tr("对应距离层级"));
    if (error && !error->isEmpty()) return options;
    if (options.voxelLevels.size() != options.correspondenceDistances.size()
        || options.voxelLevels.size() != 3) {
        if (error) *error = tr("参考流程要求三个体素层级和三个对应距离，数量必须一致");
        return options;
    }
    options.maximumCorrectionTranslation = float(ui->dsb_max_translation->value());
    options.maximumCorrectionAngleDegrees = float(ui->dsb_max_rotation->value());
    return options;
}

void StitchingWindow::startStitching()
{
    if (m_watcher && m_watcher->isRunning()) return;
    QString error;
    const QVector<pointcloud::WorldCloudInput> inputs = collectInputs(&error);
    if (!error.isEmpty()) {
        QMessageBox::warning(this, tr("输入无效"), error);
        return;
    }
    const pointcloud::IcpOptions icp = collectIcpOptions(&error);
    if (!error.isEmpty()) {
        QMessageBox::warning(this, tr("参数无效"), error);
        return;
    }
    const QString output = QDir::fromNativeSeparators(ui->le_output_directory->text().trimmed());
    if (output.isEmpty()) {
        QMessageBox::warning(this, tr("输出无效"), tr("请选择输出目录"));
        return;
    }

    m_cancelRequested = std::make_shared<std::atomic_bool>(false);
    m_watcher = new QFutureWatcher<StitchTaskResult>(this);
    connect(m_watcher, &QFutureWatcher<StitchTaskResult>::finished,
            this, &StitchingWindow::stitchingFinished);
    setBusy(true);
    appendLog(tr("开始：%1 个点云；模式=%2；机器人坐标转换=开启；ICP=%3")
                  .arg(inputs.size())
                  .arg(icp.enabled ? tr("配准与融合") : tr("仅手眼坐标转换"))
                  .arg(icp.enabled ? tr("开启") : tr("关闭")));
    const double previewRatio = ui->dsb_preview_ratio->value();
    const bool writeSources = true;
    SeamFusionOptions seamOptions;
    seamOptions.enabled = icp.enabled && ui->chk_seam_fusion->isChecked();
    seamOptions.halfWidth = float(ui->dsb_seam_half_width->value());
    seamOptions.mutualDistance = float(ui->dsb_mutual_distance->value());
    seamOptions.decisionCellSize = float(ui->dsb_decision_voxel->value());
    const auto progress = [this](int value, const QString &message) {
        QMetaObject::invokeMethod(this, [this, value, message]() {
            ui->pbar_progress->setValue(value);
            ui->pbar_progress->setFormat(QStringLiteral("%1%  %2").arg(value).arg(message));
            statusBar()->showMessage(message);
            appendLog(message);
        }, Qt::QueuedConnection);
    };
    m_watcher->setFuture(QtConcurrent::run([inputs, icp, seamOptions, output, previewRatio, writeSources,
                                            cancel = m_cancelRequested, progress]() {
        return runStitching(inputs, icp, seamOptions, output, previewRatio, writeSources, cancel, progress);
    }));
}

void StitchingWindow::cancelStitching()
{
    if (m_cancelRequested) m_cancelRequested->store(true);
    ui->btn_cancel->setEnabled(false);
    statusBar()->showMessage(tr("已请求取消；将在当前计算/输出阶段结束后停止"));
}

void StitchingWindow::stitchingFinished()
{
    const StitchTaskResult result = m_watcher->result();
    m_watcher->deleteLater();
    m_watcher = nullptr;
    setBusy(false);
    appendLog(result.merge.diagnostics);
    if (result.cancelled) {
        appendLog(tr("任务已取消。已经写出的文件不会自动删除。"));
        statusBar()->showMessage(tr("已取消"));
        return;
    }
    if (!result.ok) {
        appendLog(tr("失败：%1").arg(result.error));
        QMessageBox::critical(this, tr("配准失败"), result.error);
        return;
    }
    appendLog(tr("完成：合并 %1 点；跨点云重复 %2；预览 %3 点\n输出：%4\n报告：%5")
                  .arg(result.merge.points.size())
                  .arg(result.merge.crossCloudDuplicateCount)
                  .arg(result.previewCount)
                  .arg(result.mergedFile, result.reportFile));
    statusBar()->showMessage(result.transformOnly
        ? tr("手眼坐标转换和输出完成") : tr("点云配准和输出完成"));
    QMessageBox::information(this, tr("完成"), result.transformOnly
        ? tr("已生成手眼转换后的机器人基坐标点云：\n%1").arg(result.mergedFile)
        : tr("已生成机器人基坐标合并点云：\n%1").arg(result.mergedFile));
}

void StitchingWindow::updateProcessingModeUi()
{
    const bool registrationMode = ui->cb_processing_mode->currentIndex() == 0;
    ui->chk_icp->setChecked(registrationMode);
    ui->le_voxel_levels->setEnabled(registrationMode);
    ui->le_correspondence_distances->setEnabled(registrationMode);
    ui->le_iterations->setEnabled(registrationMode);
    ui->dsb_overlap_margin->setEnabled(registrationMode);
    ui->dsb_max_translation->setEnabled(registrationMode);
    ui->dsb_max_rotation->setEnabled(registrationMode);
    ui->chk_seam_fusion->setEnabled(registrationMode);
    ui->dsb_seam_half_width->setEnabled(registrationMode);
    ui->dsb_mutual_distance->setEnabled(registrationMode);
    ui->dsb_decision_voxel->setEnabled(registrationMode);
    ui->btn_start->setText(registrationMode
        ? tr("开始世界坐标配准") : tr("开始手眼坐标转换"));
    ui->pte_log->setPlaceholderText(registrationMode
        ? tr("转换、重叠检查、ICP、接缝和输出报告将显示在这里。")
        : tr("读取、手眼坐标转换和输出进度将显示在这里。"));
    statusBar()->showMessage(registrationMode
        ? tr("添加三个 ASCII PLY，并填写对应扫描 Start/End 位姿")
        : tr("添加一个或多个 ASCII PLY，转换后不执行 ICP 或接缝融合"));
}

void StitchingWindow::setBusy(bool busy)
{
    ui->gb_paths->setEnabled(!busy);
    ui->tbl_scans->setEnabled(!busy);
    ui->gb_options->setEnabled(!busy);
    ui->btn_add_files->setEnabled(!busy);
    ui->btn_add_folder->setEnabled(!busy);
    ui->btn_remove_rows->setEnabled(!busy);
    ui->btn_clear_files->setEnabled(!busy);
    ui->btn_start->setEnabled(!busy);
    ui->btn_cancel->setEnabled(busy);
    ui->pbar_progress->setRange(0, 100);
    if (busy) {
        ui->pbar_progress->setValue(0);
        ui->pbar_progress->setFormat(tr("0%  准备开始"));
    }
}

void StitchingWindow::appendLog(const QString &text)
{
    if (text.trimmed().isEmpty()) return;
    ui->pte_log->appendPlainText(QStringLiteral("[%1] %2")
        .arg(QDateTime::currentDateTime().toString(QStringLiteral("HH:mm:ss")), text.trimmed()));
}
